Update translation scripts (will remove line numbers)

diff --git a/package/translate/plasmoidlocaletest b/package/translate/plasmoidlocaletest
--- a/package/translate/plasmoidlocaletest
+++ b/package/translate/plasmoidlocaletest
@@ -1,61 +1,81 @@
 #!/bin/bash
-# Version 1
+# Version 6
 # Requires plasmoidviewer v5.13.0
 
 function checkIfLangInstalled {
-	dpkg -l ${1} >/dev/null 2>&1 || ( \
-		echo -e "${1} not installed.\nInstalling now before continuing.\n" \
-		; sudo apt install ${1} \
-	) || ( \
-		echo -e "\nError trying to install ${1}\nPlease run 'sudo apt install ${1}'\n" \
-		; exit 1 \
-	)
+	if [ -x "$(command -v dpkg)" ]; then
+		dpkg -l ${1} >/dev/null 2>&1 || ( \
+			echo -e "${1} not installed.\nInstalling now before continuing.\n" \
+			; sudo apt install ${1} \
+		) || ( \
+			echo -e "\nError trying to install ${1}\nPlease run 'sudo apt install ${1}'\n" \
+			; exit 1 \
+		)
+	elif [ -x "$(command -v pacman)" ]; then
+		# TODO: run `locale -a` and check if the locale is enabled.
+		if false; then
+			# https://wiki.archlinux.org/index.php/Locale
+			# Uncomment the locale in /etc/locale.gen
+			# Then run `locale-gen`
+			echo -e "\nPlease install this locale in System Settings first.\n"
+			exit 1
+		else
+			echo ""
+		fi
+	else
+		echo -e "\nPackage manager not recognized. If the widget is not translated, please install the package '${1}'\n"
+	fi
 }
 
-lang="${1}"
-languagePack="language-pack-$lang"
+langInput="${1}"
+lang=""
+languagePack=""
 
-
-if [ "$lang" == *":"* ]; then # String contains a colon so assume it's a locale code.
+if [[ "$langInput" =~ ":" ]]; then # String contains a colon so assume it's a locale code.
+	lang="${langInput}"
 	IFS=: read -r l1 l2 <<< "${lang}"
-elif [ "$lang" == "bg" ]; then # Bulgarian (Bulgaria)
-	lang="bg_BG:bg"
-elif [ "$lang" == "de" ]; then # German (Germany)
-	lang="de_DE:de"
-elif [ "$lang" == "el" ]; then # Greek (Greece)
-	lang="el_GR:el"
-elif [ "$lang" == "es" ]; then # Spanish (Mexico)
-	lang="es_MX:es"
-elif [ "$lang" == "fr" ]; then # French (Canada)
-	lang="fr_CA:fr"
-elif [ "$lang" == "nl" ]; then # Dutch (Netherlands)
-	lang="nl_NL:nl"
-elif [ "$lang" == "pl" ]; then # Polish (Poland)
-	lang="pl_PL:pl"
-elif [ "$lang" == "pt" ]; then # Portuguese (Brazil)
-	lang="pt_BR:pt"
-elif [ "$lang" == "ru" ]; then # Russian (Russia)
-	lang="ru_RU:ru"
-elif [ "$lang" == "uk" ]; then # Ukrainian (Ukraine)
-	lang="uk_UA:uk"
-elif [ "$lang" == "zh_CN" ]; then # Chinese (China)
-	lang="zh_CN:zh"
-	languagePack="language-pack-zh-hans"
-else
+	languagePack="language-pack-${l2}"
+fi
+
+declare -a langArr=(
+	"ar_EG:ar:Arabic (Egypt)"
+	"bg_BG:bg:Bulgarian (Bulgaria)"
+	"da_DK:da:Danish (Denmark)"
+	"de_DE:de:German (Germany)"
+	"el_GR:el:Greek (Greece)"
+	"es_MX:es:Spanish (Mexico)"
+	"fr_CA:fr:French (Canada)"
+	"hr_HR:hr:Croatian (Croatia)"
+	"id_ID:id:Indonesian (Indonesia)"
+	"ko_KR:ko:Korean (South Korea)"
+	"nl_NL:nl:Dutch (Netherlands)"
+	"pl_PL:pl:Polish (Poland)"
+	"pt_BR:pt:Portuguese (Brazil)"
+	"ru_RU:ru:Russian (Russia)"
+	"tr_TR:tr:Turkish (Turkey)"
+	"uk_UA:uk:Ukrainian (Ukraine)"
+	"zh_CN:zh:Chinese (China)"
+)
+
+for i in "${langArr[@]}"; do
+	IFS=: read -r l1 l2 l3 <<< "$i"
+	if [ "$langInput" == "$l2" ]; then
+		lang="${l1}:${l2}"
+		languagePack="language-pack-${l2}"
+	fi
+done
+
+if [ -z "$lang" ]; then
 	echo "plasmoidlocaletest doesn't recognize the language '$lang'"
 	echo "Eg:"
 	scriptcmd='sh ./plasmoidlocaletest'
-	echo "    $scriptcmd bg     | Bulgarian (Bulgaria)"
-	echo "    $scriptcmd de     | German (Germany)"
-	echo "    $scriptcmd el     | Greek (Greece)"
-	echo "    $scriptcmd es     | Spanish (Mexico)"
-	echo "    $scriptcmd fr     | French (Canada)"
-	echo "    $scriptcmd nl     | Dutch (Netherlands)"
-	echo "    $scriptcmd pl     | Polish (Poland)"
-	echo "    $scriptcmd pt     | Portuguese (Brazil)"
-	echo "    $scriptcmd ru     | Russian (Russia)"
-	echo "    $scriptcmd uk     | Ukrainian (Ukraine)"
-	echo "    $scriptcmd zh_CN  | Chinese (China)"
+	for i in "${langArr[@]}"; do
+		IFS=: read -r l1 l2 l3 <<< "$i"
+		echo "    ${scriptcmd} ${l2}     | ${l3}"
+	done
+	echo ""
+	echo "Or use a the full locale code:"
+	echo "    ${scriptcmd} ar_EG:ar"
 	exit 1
 fi
 
@@ -63,12 +83,21 @@ IFS=: read -r l1 l2 <<< "${lang}"
 l1="${l1}.UTF-8"
 
 # Check if language is installed
-checkIfLangInstalled "$languagePack" || exit 1
+if [ ! -z "$languagePack" ]; then
+	if [ "$lang" == "zh_CN:zh" ]; then languagePack="language-pack-zh-hans"
+	fi
+
+	checkIfLangInstalled "$languagePack" || exit 1
+fi
+
 
 echo "LANGUAGE=\"${lang}\""
 echo "LANG=\"${l1}\""
 
-# Build local translations for plasmoidviewer
-sh ./build
+scriptDir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+packageDir="${scriptDir}/.."
 
-LANGUAGE="${lang}" LANG="${l1}" QML_DISABLE_DISK_CACHE=true plasmoidviewer -a .. -l topedge -f horizontal -x 0 -y 0
+# Build local translations for plasmoidviewer
+sh "${scriptDir}/build"
+
+LANGUAGE="${lang}" LANG="${l1}" LC_TIME="${l1}" QML_DISABLE_DISK_CACHE=true plasmoidviewer -a "$packageDir" -l topedge -f horizontal -x 0 -y 0
